apiVersion: v1
kind: Pod
metadata:
  name: hmao-2gpu-pods
  namespace: sgeiger-capstone
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: nvidia.com/gpu.product
                operator: NotIn
                values:
                  - "NVIDIA-A100-PCIE-40GB"
  containers:
  - name: gpu-container
    image: staeiou/unsloth-nrp:latest
    env:
      - name: HF_HOME
        value: /workspace/.cache/huggingface
      - name: HF_DATASETS_CACHE
        value: /workspace/.cache/huggingface/datasets
      - name: UV_CACHE_DIR
        value: /workspace/.cache/uv
      - name: PIP_CACHE_DIR
        value: /workspace/.cache/pip
      - name: HF_TOKEN
        valueFrom:
          secretKeyRef:
            name: hf-token
            key: token
      - name: GITHUB_PAT
        value: ""
    command: ["/bin/bash", "-lc"]
    args:
    - |
      sleep infinity
    resources:
      limits:
        nvidia.com/a100: 2
        cpu: "2"
        memory: 32Gi
        ephemeral-storage: 458Gi
      requests:
        nvidia.com/a100: 2
        cpu: "2"
        memory: 32Gi
        ephemeral-storage: 458Gi
    volumeMounts:
      - name: hfhome-ephemeral
        mountPath: /workspace
      - name: dshm
        mountPath: /dev/shm
  volumes:
    - name: hfhome-ephemeral
      emptyDir:
        sizeLimit: 450Gi
    - name: dshm
      emptyDir:
        medium: Memory
        sizeLimit: 8Gi
  restartPolicy: Never
